spring:
  application:
    name: homepage-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #是否从 Eureka Server 中获取注册信息，默认为true
    fetch-registry: false
    #是否将自己注册到Eureka Server 默认为true
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
